### PR TITLE
Summary panel, re-skinned timeline and easier to select timeline events

### PR DESCRIPTION
**Pull request by peterwmwong**
screen shot 2017-05-06 at 11 52 14 pm

Here's the increased hit area timeline events:
sp-increased-hit-area

# TODO

- [ ] 1. Redo Timeline to handle many events
- [ ] 2. Breakdown list needs a max height/scroll/shadow

### CODE REVIEW

**Comment by peterwmwong** [comment]
@ddrscott Ready for review.

**Comment by ddrscott** [comment]
When connecting this into a more substantial Rails project it becomes unusable :(.
Add this to the "other" project's Gemfile, and you'll see what I mean.

```ruby
  gem 'sql_probe', path: '../sql_probe'
  # Webricks doesn't support Websockets. Puma does.
  gem 'puma'
```

sadness

Broken things are:
- unusable performance. My guess is something needs to be debounced.
- can't access all statements in summary panel when there is a large list of unique statements or a single statement is many many lines.
- can't see SQL statement after selecting a single event in timeline when list of unique statements is more than window's height.

I'll try to make the `spec/dummy` app reflect the problems and/or Hipaatitis.

**Comment by ddrscott** [comment]
I added a naughty controller to `spec/dummy` so we can generate some super bad actions.

Here's an updated demo showing the bottom summary chart not showing all the statements:
sadness2

**Comment by peterwmwong** [comment]
@ddrscott Thanks for putting it through it's paces to flush out these issues.  I've made some todos in the PR description for the first 2 points you've made.

As for the 3rd point...

> * can't see SQL statement after selecting a single event in timeline when list of unique statements is more than window's height.

Can't tell from the gif, but I suspect you weren't horizontally scrolled to where those SQL statements  were executed.  But I think if this is actually an issue, it'll be moot with TODO to redo the timeline.

**Comment by peterwmwong** [comment]
@ddrscott Feel free to add more TODOs in the description!

**Comment by ddrscott** [comment]
I'll take what you got. It's kinda in a broken state even before this PR and I didn't want this and my other PR to diverge too far.

I'll open up new issues for the TODOs so we don't lose them and get the pivot stuff in the tab you've created. Thanks!

**Pull request merged**
